### PR TITLE
bump bal_tools version

### PR DESCRIPTION
**Pull request by jalbrekt85**
uses new core pool model here -  https://github.com/BalancerMaxis/bal_tools/pull/37
it behaves like a dict where we need it to, so there should be no breaking changes
can be merged after bal_tools v0.1.8 is released

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
@jalbrekt85 can we get the tests working?

**Comment by gosuto-inzasheru** [comment]
this is still a draft; needs a new release from bal_tools first

**Comment by gosuto-inzasheru** [comment]
shit i merged https://github.com/BalancerMaxis/bal_addresses/pull/454 into here

**Comment by Tritium-VLK** [comment]
Don't forget to bump the version in setup.py line 3.

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
