### PR TITLE
Add origin ARB injector

### PR DESCRIPTION
**Pull request by Tritium-VLK**
A second $ARB injector to be used by the origin protocol for their injections that have nothing to do with our STIP funds.

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Multisig transaction to configure upkeep: https://app.onchainden.com/safes/arb1:0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e/transactions/0x5172ad360f55ba63b614f4c360eed5f4b114eb6e106438ff41dedd2eb9e6e88b?nid=325666

Tenderly: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/5ecf005b-c9a9-48c4-8033-d540c7b27311

Expected upkeep id: `86859634679590626033121271277707779505599940906660121431015848004435828359506`

**Comment by Tritium-VLK** [comment]
Expected upkeep ID was false.  Here is the link to the [Chainlink Automation Instance](https://automation.chain.link/arbitrum/57699741806029293769863938639399199978344467143644314533146559301381084933012) where balances can be observed and more link can be paid in to cover gas costs.   It's probably good for a few runs now. 

UpkeepId is: `57699741806029293769863938639399199978344467143644314533146559301381084933012`

Keeper updated to proper forwarder address: https://arbiscan.io/tx/0xe11cd36ff56c0ac5a28d610d361a86903aeaf07f0102522b799156f40ff8c63f

**Review by gosuto-inzasheru — COMMENTED** [review]
- arb token
- keeper set to forwarder address from chainlink ui
- no gauges added yet

wouldnt it be better if the owner was set to the omnichain lm msig though?

**Comment by gosuto-inzasheru** [comment]
for ref, upkeep config tx: https://arbiscan.io/tx/0x75f04be93635e0fc6d4ca36232507a7f69fc8479f816dfd9535107f5ddb36507

**Comment by Tritium-VLK** [comment]
> * arb token
> * keeper set to forwarder address from chainlink ui
> * no gauges added yet
> 
> wouldnt it be better if the owner was set to the omnichain lm msig though?

Right now all the money is still in the LM multisig, and owner kinda does config and tends to pay in bags.  We should get tehre, but this is kind of a slow change.  For now just getting this safe out there and in some kind of operation is a good first step.

We can do a larger migration, but that should be a planned project with some focus.

**Review by gosuto-inzasheru — APPROVED** [review]

**Pull request merged**
