### PR TITLE
Arbitrum DAO KYC

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Setup Multisig for handling $ARB from the DAO grant.

Requires a majority of signers to KYC with Arbitrum (but not otherwise dox).

KYCed signers will be named as kycsigner1 - kycsigner3.  

I certify that these are 3 different people all of whom are connected to Balancer.  The Arbitrum KYC process will do the same.

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Final Signer list:
image


Zendragon: `arb1:0x7c2eA10D3e5922ba3bBBafa39Dc0677353D2AF17`
Tritium: `arb1:0xcf4fF1e03830D692F52EB094c52A5A6A2181Ab3F`

Are already known addresses that will not KYC, but exist in bal_addresses and have history of operating with balancer multisigs.

Will ask the 3 new kyc signers to load up a transaction that sends 0 arb to the grant safe.  This transaction will be executed as on-chain record of signer liveliness.

**Comment by Tritium-VLK** [comment]
Proof of liveliness from KYC signers.  All 3 signed this TX:

https://app.safe.global/transactions/tx?id=multisig_0xb6BfF54589f269E248f99D5956f1fDD5b014D50e_0x192e580eba1b6d3925812f31ad5f08e649eb38557fc99e125309e3201e4d000a&safe=arb1:0xb6BfF54589f269E248f99D5956f1fDD5b014D50e

**Comment by Tritium-VLK** [comment]
Safe and signers are verified:
https://app.safe.global/home?safe=arb1:0xb6BfF54589f269E248f99D5956f1fDD5b014D50e

**Comment by Tritium-VLK** [comment]
@Zen-Maxi as the other known Maxi signer on this safe, can you just review this PR and the process and make sure it all looks kosher.  Then go ahead and approve/merge this PR.

**Review by Zen-Maxi — APPROVED** [review]
Straight forward enough to me. Looks good.

**Pull request merged**
