### PR TITLE
chore: add dao multisig on fantom

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Solves #216

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
https://safe.fantom.network/home?safe=ftm:0xFe2022da08d17ac8388F5bEFE4F71456255105A4

**Comment by Tritium-VLK** [comment]
image


Need to find more signers, right now this is a 6/11 msig with only 4 known signers.  Don't think we should add this to bal_addresses until we have control of it,.

**Comment by Tritium-VLK** [comment]
Ok so we need more of a plan here.  This is what I suggest.

1: Launch a new safe on fantom with maxi signers.
2: Load up 1 tx to claim and send the beets to the safe created in 1 (@solarcurvey  can load it)
3: Search the earth for enough signers to make it so and exec when we get there.


I don't think the beets is that much value/is ok in a safe with Maxi signers.  @Xeonus @mikebmikeb @0xDanko sound good?

**Comment by 0xDanko** [comment]
What happened to bridging it to Optimism, there's no bridge? I don't mind if you guys want to have this sitting idle or do something with it, as long as it has a gov vote to support. But honestly, it kinda strays away from Maxis scope of work moving forward if you're not doing anything with it. Plus, this could sit anywhere else that is not under management of US-persons for no reason. Even giving it to Karpatkey seems like a better idea IMO.

**Comment by Tritium-VLK** [comment]
@0xDanko updated the bip to get it to OP. Karpatkey only operates on mainnet right now, so that's not really an option at the moment, but I agree.

**Comment by 0xDanko** [comment]
This is DAO Treasury on Op
https://optimistic.etherscan.io/address/0x043f9687842771b3dF8852c1E9801DCAeED3f6bc

**Comment by Tritium-VLK** [comment]
Note that I asked Fernando to try to get in contact with 2-3 of the unknown signers on the safe so we can take control and recover the beets.

**Comment by gosuto-inzasheru** [comment]
ah i never saw this pr

i think it can be closed, these changes are already included in #264 and #267 

also needed some adjustments in the multisig ops repo to get sims going (https://github.com/BalancerMaxis/multisig-ops/pull/916/files):

Screenshot 2024-04-25 at 15 17 12

**Comment by gosuto-inzasheru** [comment]
only diff now is the dao msig on fantom, which is good to have on file of course

**Review by Xeonus — APPROVED** [review]

**Pull request merged**
