### PR TITLE
chore: add mimic smartvault v2

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**

### CODE REVIEW

**Comment by Xeonus** [comment]
@gosuto-inzasheru: according to Mimic this should be smart vault v3, not v2.

So to clarify from my understanding:
- Smartvault v2: 0x94dd9c6152a2a0bbcb52d3297b723a6f01d5f9f7 (we just called it smartvault unti now AFAIK, see (this)[https://forum.balancer.fi/t/bip-294-authorize-mimic-smart-vault-on-arbitrum/4779] proposal)
- Smartvault v3: 0x9e5d6427d2cdadc68870197b099c2df535ec3c97

**Comment by gosuto-inzasheru** [comment]
@Xeonus i didnt want to introduce breaking changes renaming `"smartvault"` to `"smartVaultV2"`, so only did so for the v3

**Review by Tritium-VLK — CHANGES_REQUESTED** [review]
We should leave the v2 address in there too.

**Comment by gosuto-inzasheru** [comment]
can you elaborate on the changes needed @Tritium-VLK, it is not making any sense to me

**Review by Tritium-VLK — APPROVED** [review]

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
