### PR TITLE
Add Hypernative Signer

### PR DESCRIPTION
**Pull request by Tritium-VLK**

### CODE REVIEW

**Comment by gal-hypernative** [comment]
I can confirm as Hypernative CEO that the added address belongs to Hypernative

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru has asked for a bit more support to confirm this address:

|I can confirm that @gal-hypernative is the CEO of Hypernative, and is the same person who wrote this BIP that was approved by governance.

https://forum.balancer.fi/t/bip-456-funding-hypernative-as-balancer-security-advisor/5244

@gal-hypernative could you maybe just post a comment on the BIP test from your Forum account confirming this is your github Id?

**Comment by gal-hypernative** [comment]
Done, i have left a comment on the forum

**Comment by Tritium-VLK** [comment]
https://forum.balancer.fi/t/bip-456-funding-hypernative-as-balancer-security-advisor/5244/6?u=tritium

**Review by gosuto-inzasheru — APPROVED** [review]

**Pull request merged**
