### PR TITLE
found: Emissions schedule

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Found this emissions schedule in another repo.  It seems useful and should maybe end up in bal_addresses outputs.  Not quite sure if the input data should live here in extras or be part of bal_tools.  Figured I'd just check it in and ask for comment.

@jalbrekt85 @gosuto-inzasheru thoughts?

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
good to have on file! i would think it makes more sense in bal tools though, i dont really see how it is related to the address book :)

**Comment by Tritium-VLK** [comment]
Agreed @jalbrekt85 do you maybe want to copy this into bal_tools and create some function to read it?

@gosuto-inzasheru the one thing I do think could be useful is an output file in outputs that is autogened based on the bal_tools functionality, just because we have maps to sueful things in the DAO, and that's another thing that is hard to find.

**Comment by gosuto-inzasheru** [comment]
im not sure what kind of output file you are suggesting, what kind of mapping is currently missing?

**Comment by Tritium-VLK** [comment]
> im not sure what kind of output file you are suggesting, what kind of mapping is currently missing?

As a non-python(js) user looking at the outputs folder, it woudl be nice to find an "emissionsSchedule.json" or some kind of an artifact to help you understand this.  This is one of the great mysteries at Balacner that most people do not understand.

The only greater mystery is exactly when in the year it rolls over, that I am not sure anyone has ever figured out...  

We could also do this later or thinka bout it another way.  The only other place this is well expressed is in the docs where it is quite hard to get it in json/programatic format.

**Comment by Tritium-VLK** [comment]
Fina note here.  The current output is in the format that came from the docs and is required to make a graph.  The bal_addresses output format tends to be a bit more heirartical with less metadata.

so for example it seems like emissions[year] should return an int perhaps?

**Comment by jalbrekt85** [comment]
closing in favor of: https://github.com/BalancerMaxis/bal_tools/issues/11
can continue discussion there

**Pull request closed without merging**
