### PR TITLE
chore: add backup signers

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
as per https://forum.balancer.fi/t/bip-681-update-dao-multisig-signers-and-backup-signers/

still need confirmation from anna and hubert

### CODE REVIEW

**Comment by TREBUH-Tube** [comment]
Hubert from Stake DAO, I confirm that I control this address: 0x02e4De712d99f4B1b1e12aa3675D8b0A582caA5D

**Comment by Tritium-VLK** [comment]
> Hubert from Stake DAO, I confirm that I control this address: 0x02e4De712d99f4B1b1e12aa3675D8b0A582caA5D

Thanks for this Hubert, but still need something with a bit more history/etc.  Will speak in DM and come back with the next step :).

Finally thank you to all our new signers for dealing with this, and sorry it is a pain.  It's worthwhile to make sure we know who our signers are, that this is transparent, that folks like Chris Blech won't put us on the top of their "list", and that we minimize the amount of trust required in me/the maxis to confirm our signer-set is secure.

**Comment by Tritium-VLK** [comment]
It doesn't seem like we will be able to complete a thorough identification process for Anna right now, so will leave her out of the address_book and get this done before/if we ever add her as a backup signer.

**Review by Tritium-VLK — APPROVED** [review]

**Comment by Tritium-VLK** [comment]
@Xeonus you mind stamping this as gos opened it and I was the last commitooor?

**Review by Xeonus — APPROVED** [review]

**Pull request merged**
