### PR TITLE
chore: Prune core pools

### PR DESCRIPTION
**Pull request by Tritium-VLK**
down to non-50% IB pools that should be + eCLPs that were already there.
 
 Depending on TVL some of the removed pools may still qualify to be core pools, but as I understand it we don't need them
 
 mevETH has governance specifically adding itot the core pools list: https://forum.balancer.fi/t/bip-466-enable-meveth-weth-gauge-ethereum/5285
 
 I think most of the other ones on there that are not at least 50% ib do as well if you care to try to find it. 
 https://forum.balancer.fi/t/bip-210-deprecate-old-stargate-gauges-add-gauges-for-stg-v2/4472
 
 I couldn't find anything for the GHO pool but aave are frens and I think it was intended. 
 

@gosuto-inzasheru can we remove eCLPs too, if so go ahead and dos o.  Then we should just check the diff of a core pools run with this list vs a core pools run with no whitelist. 

Solves #184

### CODE REVIEW

**Comment by Xeonus** [comment]
- @Tritium-VLK just for clarification: will we now dynamically add / remove these non-50% IB pools based on this new automation? Do we need governance for that?
- GHO: they didn't specify that in their proposal but fully agree to go core on those (if metrics say so)

**Review by gosuto-inzasheru — APPROVED** [review]
@Tritium-VLK `ECLP-swETH-wstETH` and `ECLP-mevETH-wETH` are both too low in liq to be included automatically ($101k and $242k respectively). not sure if we want to make an exception for them or remove them from the whitelist for now, and let them appear automatically once they reach the liquidity threshold of $250k.

here some dd to show why the rest of the removed pools arent included currently through the automation:

mainnet
- 50wstETH-50LDO: too low liq ($163k)
- 50rETH-50BADGER: too low liq ($30k)
- ETHx-WETH: too low liq ($11k)
- 80RDNT-20wETH: no yield bearing
- 80mevETH-20FOLD: too low liq ($0k)
- sDAI-DUSD: too low liq ($3k)
- weETH-WETH: too low liq ($113k)

polygon
- stMATIC-WMATIC: too low liq ($0k)
- wstETH-WETH: too low liq ($0k)

zkevm
- ankrETH-wstETH: too low liq ($221k)
- wstETH/rETH: too low liq ($202k)

arb1:
- ANKR:ankrETH: too low liq ($0k)
- wstETH:4pool: too low liq ($11k)

avax:
- EURe/USDC: no yield bearing

opti:
- frxETH/sfrxETH: too low liq ($71k)

so good thing to note here is that most of these pools will reappear in the core pools json automatically once they regain enough depth.

**Comment by gosuto-inzasheru** [comment]
btw, in regards to $gho, there are also these two $gho/$usdc pools coming up: https://forum.balancer.fi/t/bip-539-enable-gho-usdc-e-clp-gho-gyd-e-clp-gauges/5527

**Comment by Tritium-VLK** [comment]
There is no reason to have core pools on the list with under 250k TVL, because they are highly unlikely to generate over 500 bucks per 2 week period in fees and therefore won't do anything anyway.

As a result I removed the 3 mainnet eCLPs as all 3 are at least 50% yield bearing anyway.

I am not sure if it is recorded, it may be, but each chain should have 1 3 or 4 pool for core USD liquidty that is core.  You can see these are represented.

RDNT, ALCX and STG have specific callouts in the BIP.

You are correct that the only remaining question is what to do about the GHO 3pool on the list, and the other GHO pools not on it, which are also <50% yield bearing.

GHO/USDC/USDT is added but there is no mention of a special addition of core pool status in the BIP: https://forum.balancer.fi/t/bip-411-enable-gho-usdt-usdc-gauge-ethereum/5135

It has been receiving core pool bribs tho, so removing it would kind of deflate the pool without much notice.   My feeling is that we should just grandfather this one in, but not add any other GHO pools to the list unless there is specific governance that states it should be there.

I think this looks good and ready to merge now as a result.  Will get some input from a few more Maxis.

**Comment by Tritium-VLK** [comment]
Missed USDF:
https://forum.balancer.fi/t/bip-418-enable-usdf-usdc-gauge-arbitrum/5100

Governance has nothing about core pools, it is getting no bribs, removed it.

**Comment by gosuto-inzasheru** [comment]
lgtm

**Review by gosuto-inzasheru — APPROVED** [review]
lgtm!

**Comment by Tritium-VLK** [comment]
@Xeonus the best thing to do would be to make a BIP to ratify the legacy of GHO/USDT/USDC being on the core pools list and adding any other GHO pools that should also be on it.  It should have some justification as to why/etc.  Otherwise we can just "not touch it".

**Pull request merged**
